#!/bin/tcsh

if ( $#argv == 1) then
  echo "Running left thalamus"
  ~/thomas_new/THOMAS.py -a v2 -p 4 -v --jointfusion --tempdir temp $1 ALL
else
  if ( $#argv == 2) then
    if ($2 == r) then
      echo "Running left and right thalamus"
      echo "Running left thalamus"
      ~/thomas_new/THOMAS.py -a v2 -p 4 -v --jointfusion --tempdir temp $1 ALL
      mkdir left
      mv *.nii.gz left
      mv temp/*Warp* temp/*Aff* left
      mv temp/registered.nii.gz left
      mv left/$1 .
      echo "Running right thalamus"
      ~/thomas_new/THOMAS.py -a v2 -p 4 -v -R --jointfusion --tempdir tempr $1 ALL
    else
      echo "Usage: thomas <wmnfile> or thomas <wmnfile> r"
    endif
  else
      echo "Usage: thomas <wmnfile> or thomas <wmnfile> r"
  endif
endif

